// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shengsiyuan.proto;

public interface IntReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.IntReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
