// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shengsiyuan.proto;

public interface StreamReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.StreamReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req_info = 1;</code>
   */
  java.lang.String getReqInfo();
  /**
   * <code>string req_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqInfoBytes();
}
