// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shengsiyuan.proto;

public interface StreamRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.StreamResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resp_info = 1;</code>
   */
  java.lang.String getRespInfo();
  /**
   * <code>string resp_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getRespInfoBytes();
}
