// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.shengsiyuan.proto;

public interface StreamListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.shengsiyuan.proto.StreamListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.shengsiyuan.proto.StreamResponse streamResponse = 1;</code>
   */
  java.util.List<com.shengsiyuan.proto.StreamResponse> 
      getStreamResponseList();
  /**
   * <code>repeated .com.shengsiyuan.proto.StreamResponse streamResponse = 1;</code>
   */
  com.shengsiyuan.proto.StreamResponse getStreamResponse(int index);
  /**
   * <code>repeated .com.shengsiyuan.proto.StreamResponse streamResponse = 1;</code>
   */
  int getStreamResponseCount();
  /**
   * <code>repeated .com.shengsiyuan.proto.StreamResponse streamResponse = 1;</code>
   */
  java.util.List<? extends com.shengsiyuan.proto.StreamResponseOrBuilder> 
      getStreamResponseOrBuilderList();
  /**
   * <code>repeated .com.shengsiyuan.proto.StreamResponse streamResponse = 1;</code>
   */
  com.shengsiyuan.proto.StreamResponseOrBuilder getStreamResponseOrBuilder(
      int index);
}
