spring:
  #profiles:
  #  active: dev
  application:
    name: suhenApp
  mandatory-file-encoding: utf-8
  http:
    encoding:
      enabled: true
      charset: utf-8
  kafka:
    producer:
      bootstrap-servers: 192.168.31.134:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 192.168.31.134:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://192.168.31.134:3306/lw_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: cooper
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8899


suhenConfig:
  suhenObject:
    name: Cooper
    age: 25


#logging:
#  level:
#    root: debug
#  file:
#    path: logs/suhenAppLog
mybatis:
  type-aliases-package: com.shengsiyuan.boot
  mapper-locations: classpath:mapperxml/*.xml
