spring:
  #profiles:
  #  active: dev
  application:
    name: suhenApp
  mandatory-file-encoding: utf-8
  http:
    encoding:
      enabled: true
      charset: utf-8
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


server:
  port: 8899


suhenConfig:
  suhenObject:
    name: Cooper
    age: 25


#logging:
#  level:
#    root: debug
#  file:
#    path: logs/suhenAppLog
